#!/bin/sh

source ~/.config/autobib/config

# echo $BIB_FILE_PATH
# echo $PDF_STORAGE_PATH

[ -z "$1" ] && echo "Give either a pdf file or a DOI as an argument." && exit

if [ ! -f $BIB_FILE_PATH ]; then
    echo "Make sure to configure the bib file path at ~/.config/autobib/config
            example: BIB_FILE_PATH=/path/to/the/bib/file.bib"
fi

if [ ! -d $PDF_STORAGE_PATH ]; then
    echo "Make sure to configure the pdf storage path at ~/.config/autobib/config
            example: PDF_STORAGE_PATH=/path/to/the/dir/to/store/pdfs"
fi

if [ -f "$1" ]; then
	# Try to get DOI from pdfinfo or pdftotext output.
	doi=$(pdftotext "$1" 2>/dev/null - | grep -Po "10.\d{4,9}/[-._;()/:A-Z0-9]+" -m 1) ||
	doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
    exit 1
else
	doi="$1"
fi

curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n" > /tmp/response.bib

SCRIPT_HOME=$(dirname $(readlink -f "$0"))
key=$(python $SCRIPT_HOME/add_entry.py $BIB_FILE_PATH /tmp/response.bib)

# If a file was provided, check if a key was generated and move the file to the proper place
if [ -f "$1" ]; then
    if [ "$key" != "null" ]; then
        mv $1 $PDF_STORAGE_PATH/$key.pdf
    fi
fi

rm /tmp/response.bib
